In [1]:
import pandas as pd

In [12]:
df = pd.read_csv("../data/macroalgae_final.csv", index_col = 0)
df.sample(5)

,lon,lat,locality,year,month,kingdom,class,family,genus,species,new,state,country
24162,-3.5384,48.8143,Landrellec,2008,3.0,Chromista,Phaeophyceae,Fucaceae,Fucus,Fucus serratus,"48.8143,-3.5384",Bretagne,France
24599,-5.0091,50.1558,St. Mawes,2010,1.0,Plantae,Ulvophyceae,Ulvaceae,Ulva,Ulva lactuca,"50.1558,-5.0091",England,United Kingdom
14065,3.8800,51.5600,Kats,1975,1.0,Chromista,Phaeophyceae,Fucaceae,Fucus,Fucus vesiculosus,"51.56,3.88",Zeeland,Nederland
17314,-6.0358,55.1252,Cushendun,1985,4.0,Chromista,Phaeophyceae,Fucaceae,Fucus,Fucus spiralis,"55.1252,-6.0358",Northern Ireland,United Kingdom
10055,-5.1592,51.6918,Dale,1961,6.0,Chromista,Phaeophyceae,Laminariaceae,Laminaria,Laminaria digitata,"51.6918,-5.1592",Cymru / Wales,United Kingdom